name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye # build using old glibc for compatability

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11

    - name: Compile
      run: |
        nix develop --command cmake -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_FORCE_LD=/lib64/ld-linux-x86-64.so.2
        nix develop --command cmake --build build --parallel 4

    # test the application but have to manually run the tests as its dynamic
    # linker is different
    - name: Test
      run: build/bin/tests

    # package the application with cmake
    - name: Package
      run: |
        nix develop --command cmake --build build --target package

    # release the packaged zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.zip
