name: Testing

on:
  push:
    # ignore any tags but test on all branches
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11

    - name: Compile
      run: |
        nix develop --command cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
        nix develop --command cmake --build build --parallel 4

    - name: Test
      run: |
        nix develop --command ctest --test-dir build
